export DETECTRON2_DATASETS=/data/jiangning/coco_link/
python tools/analyze_model.py --config-file projects/dino/configs/dino-swin/dino_swin_small_224_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_swin_small_22k_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_tiny_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_tiny_1k_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_tiny_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_tiny_384_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_small_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_small_1k_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_small_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_small_384_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_base_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_base_1k_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_base_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_base_384_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_large_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_large_1k_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-convnext/dino_convnext_large_384_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_convnext_large_384_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-internimage/dino_internimage_tiny_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_internimage_tiny_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-internimage/dino_internimage_small_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_internimage_small_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-internimage/dino_internimage_base_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_internimage_base_4scale_12ep.txt'
python tools/analyze_model.py --config-file projects/dino/configs/dino-internimage/dino_internimage_large_4scale_12ep.py --tasks parameter >> './eval_params_addon/dino_internimage_large_4scale_12ep.txt'
